//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPolicy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIPolicy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActionSet ID: .
        /// </summary>
        internal static string ActionID {
            get {
                return ResourceManager.GetString("ActionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Controller .
        /// </summary>
        internal static string ACtrl {
            get {
                return ResourceManager.GetString("ACtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add an ActionSet..
        /// </summary>
        internal static string AddAS {
            get {
                return ResourceManager.GetString("AddAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a Controller..
        /// </summary>
        internal static string AddCtrl {
            get {
                return ResourceManager.GetString("AddCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Proc: .
        /// </summary>
        internal static string AddProc {
            get {
                return ResourceManager.GetString("AddProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a Procedure..
        /// </summary>
        internal static string addProcedure {
            get {
                return ResourceManager.GetString("addProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add_Value.
        /// </summary>
        internal static string AddValue {
            get {
                return ResourceManager.GetString("AddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Policy (*.data)|*.data|All Files (*.*)|*.*.
        /// </summary>
        internal static string AIPolicyFilter {
            get {
                return ResourceManager.GetString("AIPolicyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;&amp;.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSet ID.
        /// </summary>
        internal static string ASID {
            get {
                return ResourceManager.GetString("ASID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new ActionSet name..
        /// </summary>
        internal static string ASName {
            get {
                return ResourceManager.GetString("ASName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ActionSet named .
        /// </summary>
        internal static string ASNamed {
            get {
                return ResourceManager.GetString("ASNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string Atk {
            get {
                return ResourceManager.GetString("Atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter1:0/1.
        /// </summary>
        internal static string AtkParam1 {
            get {
                return ResourceManager.GetString("AtkParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been added to the end of the table..
        /// </summary>
        internal static string beenAdded {
            get {
                return ResourceManager.GetString("beenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been deleted.
        /// </summary>
        internal static string beenDel {
            get {
                return ResourceManager.GetString("beenDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be_Taunted.
        /// </summary>
        internal static string BeTaunted {
            get {
                return ResourceManager.GetString("BeTaunted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast_Message.
        /// </summary>
        internal static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte Count.
        /// </summary>
        internal static string ByteCount {
            get {
                return ResourceManager.GetString("ByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls.
        /// </summary>
        internal static string Calls {
            get {
                return ResourceManager.GetString("Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_Skill.
        /// </summary>
        internal static string CastSkill {
            get {
                return ResourceManager.GetString("CastSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change_Path.
        /// </summary>
        internal static string ChangePath {
            get {
                return ResourceManager.GetString("ChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create_Timer.
        /// </summary>
        internal static string CreateTimer {
            get {
                return ResourceManager.GetString("CreateTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string CRLF {
            get {
                return ResourceManager.GetString("CRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_Skill has 1 parameter..
        /// </summary>
        internal static string CS1P {
            get {
                return ResourceManager.GetString("CS1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast_Skill[1202].
        /// </summary>
        internal static string CS1PEx {
            get {
                return ResourceManager.GetString("CS1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Controller ID entered already exists.
        ///Please try again....
        /// </summary>
        internal static string CtrlExists {
            get {
                return ResourceManager.GetString("CtrlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Controller with ID: .
        /// </summary>
        internal static string CtrlIDwith {
            get {
                return ResourceManager.GetString("CtrlIDwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Controller ID entered does not exist.
        ///Please try again....
        /// </summary>
        internal static string CtrlNoExist {
            get {
                return ResourceManager.GetString("CtrlNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl Parameter.
        /// </summary>
        internal static string CtrlParam {
            get {
                return ResourceManager.GetString("CtrlParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        internal static string Cycles {
            get {
                return ResourceManager.GetString("Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Procedure.
        /// </summary>
        internal static string Del_Proc {
            get {
                return ResourceManager.GetString("Del_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ActionSet.
        /// </summary>
        internal static string DelAction {
            get {
                return ResourceManager.GetString("DelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Action Controller.
        /// </summary>
        internal static string DelACtrl {
            get {
                return ResourceManager.GetString("DelACtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete an ActionSet..
        /// </summary>
        internal static string delAS {
            get {
                return ResourceManager.GetString("delAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete a Controller..
        /// </summary>
        internal static string DelCtrl {
            get {
                return ResourceManager.GetString("DelCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete a Procedure..
        /// </summary>
        internal static string delProc {
            get {
                return ResourceManager.GetString("delProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete_Timer.
        /// </summary>
        internal static string DelTimer {
            get {
                return ResourceManager.GetString("DelTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable_ActionSet.
        /// </summary>
        internal static string DisableAS {
            get {
                return ResourceManager.GetString("DisableAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disappear.
        /// </summary>
        internal static string Disappear {
            get {
                return ResourceManager.GetString("Disappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance_To.
        /// </summary>
        internal static string DistanceTo {
            get {
                return ResourceManager.GetString("DistanceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance_To has 1 parameter..
        /// </summary>
        internal static string DT1P {
            get {
                return ResourceManager.GetString("DT1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance_To[1].
        /// </summary>
        internal static string DT1PEx {
            get {
                return ResourceManager.GetString("DT1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit an ActionSet..
        /// </summary>
        internal static string EditAS {
            get {
                return ResourceManager.GetString("EditAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit a Condition expression..
        /// </summary>
        internal static string editCondEx {
            get {
                return ResourceManager.GetString("editCondEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit it..
        /// </summary>
        internal static string EditIt {
            get {
                return ResourceManager.GetString("EditIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit a Procedure..
        /// </summary>
        internal static string editProc {
            get {
                return ResourceManager.GetString("editProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string EIGHT {
            get {
                return ResourceManager.GetString("EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements ID.
        /// </summary>
        internal static string ElementsID {
            get {
                return ResourceManager.GetString("ElementsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable_ActionSet.
        /// </summary>
        internal static string EnableAS {
            get {
                return ResourceManager.GetString("EnableAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the ActionSet.
        /// </summary>
        internal static string EnterAS {
            get {
                return ResourceManager.GetString("EnterAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string EQUAL {
            get {
                return ResourceManager.GetString("EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to read AI Lookup Table..
        /// </summary>
        internal static string ErrAILookup {
            get {
                return ResourceManager.GetString("ErrAILookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to load file..
        /// </summary>
        internal static string ErrFileLoad {
            get {
                return ResourceManager.GetString("ErrFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Parameters incorrect.
        ///Please recheck..
        /// </summary>
        internal static string ErrParams {
            get {
                return ResourceManager.GetString("ErrParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec_ActionSet.
        /// </summary>
        internal static string Exec_AS {
            get {
                return ResourceManager.GetString("Exec_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exists..
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exit2 {
            get {
                object obj = ResourceManager.GetObject("Exit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Aggro.
        /// </summary>
        internal static string Fade_Aggro {
            get {
                return ResourceManager.GetString("Fade_Aggro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade_Aggro.
        /// </summary>
        internal static string FadeAggro {
            get {
                return ResourceManager.GetString("FadeAggro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade_Target.
        /// </summary>
        internal static string FadeTarget {
            get {
                return ResourceManager.GetString("FadeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string FIVE {
            get {
                return ResourceManager.GetString("FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flee.
        /// </summary>
        internal static string Flee {
            get {
                return ResourceManager.GetString("Flee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string FOUR {
            get {
                return ResourceManager.GetString("FOUR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FW2 {
            get {
                object obj = ResourceManager.GetObject("FW2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FW3 {
            get {
                object obj = ResourceManager.GetObject("FW3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Combat_Started has no parameter..
        /// </summary>
        internal static string ICS {
            get {
                return ResourceManager.GetString("ICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Combat_Started[].
        /// </summary>
        internal static string ICSEx {
            get {
                return ResourceManager.GetString("ICSEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (ID Control)
        ///.
        /// </summary>
        internal static string IDControl {
            get {
                return ResourceManager.GetString("IDControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Dead has no parameter..
        /// </summary>
        internal static string IDnoP {
            get {
                return ResourceManager.GetString("IDnoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Dead[].
        /// </summary>
        internal static string IDnoPEx {
            get {
                return ResourceManager.GetString("IDnoPEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Event has no parameter..
        /// </summary>
        internal static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEvent[].
        /// </summary>
        internal static string IEEx {
            get {
                return ResourceManager.GetString("IEEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_HP_Less has 1 parameter..
        /// </summary>
        internal static string IHPL1P {
            get {
                return ResourceManager.GetString("IHPL1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_HP_Less[0.80].
        /// </summary>
        internal static string IHPLEx {
            get {
                return ResourceManager.GetString("IHPLEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment_Public_Counter.
        /// </summary>
        internal static string IncPubCount {
            get {
                return ResourceManager.GetString("IncPubCount", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize_Public_Counter.
        /// </summary>
        internal static string InitPubCount {
            get {
                return ResourceManager.GetString("InitPubCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Combat_Started.
        /// </summary>
        internal static string IsCombatStarted {
            get {
                return ResourceManager.GetString("IsCombatStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Dead.
        /// </summary>
        internal static string IsDead {
            get {
                return ResourceManager.GetString("IsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Event.
        /// </summary>
        internal static string IsEvent {
            get {
                return ResourceManager.GetString("IsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_HP_Less.
        /// </summary>
        internal static string IsHPLess {
            get {
                return ResourceManager.GetString("IsHPLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Target_Dead.
        /// </summary>
        internal static string IsTargetDead {
            get {
                return ResourceManager.GetString("IsTargetDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Timer_Ticking.
        /// </summary>
        internal static string IsTimerTicking {
            get {
                return ResourceManager.GetString("IsTimerTicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Target_Dead has no parameter..
        /// </summary>
        internal static string ITD {
            get {
                return ResourceManager.GetString("ITD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Target_Dead[].
        /// </summary>
        internal static string ITDEx {
            get {
                return ResourceManager.GetString("ITDEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        internal static string ItemID {
            get {
                return ResourceManager.GetString("ItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Timer_Ticking has 1 parameter..
        /// </summary>
        internal static string ITT1P {
            get {
                return ResourceManager.GetString("ITT1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is_Timer_Ticking[0].
        /// </summary>
        internal static string ITTEx {
            get {
                return ResourceManager.GetString("ITTEx", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap JD2 {
            get {
                object obj = ResourceManager.GetObject("JD2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JD3 {
            get {
                object obj = ResourceManager.GetObject("JD3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string LBRACKET {
            get {
                return ResourceManager.GetString("LBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string LPAREN {
            get {
                return ResourceManager.GetString("LPAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string LTHAN {
            get {
                return ResourceManager.GetString("LTHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string MINUS {
            get {
                return ResourceManager.GetString("MINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob ID.
        /// </summary>
        internal static string MobID {
            get {
                return ResourceManager.GetString("MobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob Name.
        /// </summary>
        internal static string MobName {
            get {
                return ResourceManager.GetString("MobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More_Than.
        /// </summary>
        internal static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More_Than has 1 parameter..
        /// </summary>
        internal static string MT1P {
            get {
                return ResourceManager.GetString("MT1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More_Than[1].
        /// </summary>
        internal static string MT1PEx {
            get {
                return ResourceManager.GetString("MT1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string MTHAN {
            get {
                return ResourceManager.GetString("MTHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Name Control)
        ///.
        /// </summary>
        internal static string NameControl {
            get {
                return ResourceManager.GetString("NameControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string NINE {
            get {
                return ResourceManager.GetString("NINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ActionSet selected to delete..
        /// </summary>
        internal static string noAS {
            get {
                return ResourceManager.GetString("noAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expression entered..
        /// </summary>
        internal static string NoExpEntered {
            get {
                return ResourceManager.GetString("NoExpEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression between brackets do not match..
        /// </summary>
        internal static string NoMatchCond {
            get {
                return ResourceManager.GetString("NoMatchCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number was not entered into the Controller ID textbox..
        /// </summary>
        internal static string NoNumCtrl {
            get {
                return ResourceManager.GetString("NoNumCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve Conditional Expression: .
        /// </summary>
        internal static string NoResolveCond {
            get {
                return ResourceManager.GetString("NoResolveCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to switch editing mode while Mode Lock is on..
        /// </summary>
        internal static string NoSwitchMode {
            get {
                return ResourceManager.GetString("NoSwitchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        internal static string NOT {
            get {
                return ResourceManager.GetString("NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC_Generator.
        /// </summary>
        internal static string NPCGenerator {
            get {
                return ResourceManager.GetString("NPCGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player_Aimed_NPC_Spawn.
        /// </summary>
        internal static string NPCSpawn {
            get {
                return ResourceManager.GetString("NPCSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC_Vent has no parameter..
        /// </summary>
        internal static string NPCV {
            get {
                return ResourceManager.GetString("NPCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC_Vent.
        /// </summary>
        internal static string NPCVent {
            get {
                return ResourceManager.GetString("NPCVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC_Vent[].
        /// </summary>
        internal static string NPCVEx {
            get {
                return ResourceManager.GetString("NPCVEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string NULL {
            get {
                return ResourceManager.GetString("NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet available....
        /// </summary>
        internal static string NYA {
            get {
                return ResourceManager.GetString("NYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ONE {
            get {
                return ResourceManager.GetString("ONE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to open an AIPolicy file before you can .
        /// </summary>
        internal static string openAIPolicy {
            get {
                return ResourceManager.GetString("openAIPolicy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Options2 {
            get {
                object obj = ResourceManager.GetObject("Options2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path ID.
        /// </summary>
        internal static string PathID {
            get {
                return ResourceManager.GetString("PathID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path_To.
        /// </summary>
        internal static string PathTo {
            get {
                return ResourceManager.GetString("PathTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public_Counter has 1 parameter..
        /// </summary>
        internal static string PC1P {
            get {
                return ResourceManager.GetString("PC1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public_Counter[2300].
        /// </summary>
        internal static string PC1PEx {
            get {
                return ResourceManager.GetString("PC1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play_Action.
        /// </summary>
        internal static string PlayAction {
            get {
                return ResourceManager.GetString("PlayAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string PLUS {
            get {
                return ResourceManager.GetString("PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string POINT {
            get {
                return ResourceManager.GetString("POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Parameters.
        /// </summary>
        internal static string ProcParams {
            get {
                return ResourceManager.GetString("ProcParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path_To has 1 parameter..
        /// </summary>
        internal static string PT1P {
            get {
                return ResourceManager.GetString("PT1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path_To[1].
        /// </summary>
        internal static string PT1PEx {
            get {
                return ResourceManager.GetString("PT1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public_Counter.
        /// </summary>
        internal static string PubCtr {
            get {
                return ResourceManager.GetString("PubCtr", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PW1 {
            get {
                object obj = ResourceManager.GetObject("PW1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PW2 {
            get {
                object obj = ResourceManager.GetObject("PW2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QMark {
            get {
                return ResourceManager.GetString("QMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick and dirty, very basic, AIPolicy Editor..
        /// </summary>
        internal static string QnD {
            get {
                return ResourceManager.GetString("QnD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize has 1 parameter..
        /// </summary>
        internal static string R1P {
            get {
                return ResourceManager.GetString("R1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize[0.50].
        /// </summary>
        internal static string R1PEx {
            get {
                return ResourceManager.GetString("R1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank has 1 parameter..
        /// </summary>
        internal static string Ra1P {
            get {
                return ResourceManager.GetString("Ra1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank[1].
        /// </summary>
        internal static string Ra1PEx {
            get {
                return ResourceManager.GetString("Ra1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string Randomize {
            get {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string RBRACKET {
            get {
                return ResourceManager.GetString("RBRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  }.
        /// </summary>
        internal static string RCBracket {
            get {
                return ResourceManager.GetString("RCBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo history exhausted..
        /// </summary>
        internal static string RedoExh {
            get {
                return ResourceManager.GetString("RedoExh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset_Aggro.
        /// </summary>
        internal static string ResetAggro {
            get {
                return ResourceManager.GetString("ResetAggro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn.
        /// </summary>
        internal static string Respawn {
            get {
                return ResourceManager.GetString("Respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must retain at least one Procedure..
        /// </summary>
        internal static string RetainProc {
            get {
                return ResourceManager.GetString("RetainProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string RPAREN {
            get {
                return ResourceManager.GetString("RPAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Range.
        /// </summary>
        internal static string RRange {
            get {
                return ResourceManager.GetString("RRange", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save16 {
            get {
                object obj = ResourceManager.GetObject("Save16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search reached the nend of the file without results.
        ///Try searching from the beginning (Controller 1)..
        /// </summary>
        internal static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set_Mob_Attributes.
        /// </summary>
        internal static string SetMobAttr {
            get {
                return ResourceManager.GetString("SetMobAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set_Path.
        /// </summary>
        internal static string SetPath {
            get {
                return ResourceManager.GetString("SetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set_Value.
        /// </summary>
        internal static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string SEVEN {
            get {
                return ResourceManager.GetString("SEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SIX {
            get {
                return ResourceManager.GetString("SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill ID.
        /// </summary>
        internal static string Skill_ID {
            get {
                return ResourceManager.GetString("Skill_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level.
        /// </summary>
        internal static string SkillLvl {
            get {
                return ResourceManager.GetString("SkillLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string SPACE {
            get {
                return ResourceManager.GetString("SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon_Mob.
        /// </summary>
        internal static string SumMob {
            get {
                return ResourceManager.GetString("SumMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon Mob.
        /// </summary>
        internal static string SummonMob {
            get {
                return ResourceManager.GetString("SummonMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        internal static string sureDelete {
            get {
                return ResourceManager.GetString("sureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        internal static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string THREE {
            get {
                return ResourceManager.GetString("THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Interval.
        /// </summary>
        internal static string TimeInterval {
            get {
                return ResourceManager.GetString("TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer ID.
        /// </summary>
        internal static string TimerID {
            get {
                return ResourceManager.GetString("TimerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this Procedure.
        /// </summary>
        internal static string tProc {
            get {
                return ResourceManager.GetString("tProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger ID.
        /// </summary>
        internal static string TriggerID {
            get {
                return ResourceManager.GetString("TriggerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TWO {
            get {
                return ResourceManager.GetString("TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown12 has no parameter..
        /// </summary>
        internal static string U12 {
            get {
                return ResourceManager.GetString("U12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown12[].
        /// </summary>
        internal static string U12Ex {
            get {
                return ResourceManager.GetString("U12Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown13 has no parameter..
        /// </summary>
        internal static string U13 {
            get {
                return ResourceManager.GetString("U13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown13[].
        /// </summary>
        internal static string U13Ex {
            get {
                return ResourceManager.GetString("U13Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown14 has no parameter..
        /// </summary>
        internal static string U14 {
            get {
                return ResourceManager.GetString("U14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown14[].
        /// </summary>
        internal static string U14Ex {
            get {
                return ResourceManager.GetString("U14Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown15 has no parameter..
        /// </summary>
        internal static string U15 {
            get {
                return ResourceManager.GetString("U15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown15[].
        /// </summary>
        internal static string U15Ex {
            get {
                return ResourceManager.GetString("U15Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find.
        ///.
        /// </summary>
        internal static string UnableFind {
            get {
                return ResourceManager.GetString("UnableFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo history exhausted..
        /// </summary>
        internal static string UndoExh {
            get {
                return ResourceManager.GetString("UndoExh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unk {
            get {
                return ResourceManager.GetString("Unk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Condition Type: .
        /// </summary>
        internal static string UnkCondType {
            get {
                return ResourceManager.GetString("UnkCondType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Type: .
        /// </summary>
        internal static string UnkType {
            get {
                return ResourceManager.GetString("UnkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v11 Path.
        /// </summary>
        internal static string v11Path {
            get {
                return ResourceManager.GetString("v11Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value has 1 parameter..
        /// </summary>
        internal static string V1P {
            get {
                return ResourceManager.GetString("V1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value[2].
        /// </summary>
        internal static string V1PEx {
            get {
                return ResourceManager.GetString("V1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable has 1 parameter..
        /// </summary>
        internal static string Var1P {
            get {
                return ResourceManager.GetString("Var1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable[0].
        /// </summary>
        internal static string Var1PEx {
            get {
                return ResourceManager.GetString("Var1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable_Value.
        /// </summary>
        internal static string VariableValue {
            get {
                return ResourceManager.GetString("VariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable_Value has 1 parameter..
        /// </summary>
        internal static string VV1P {
            get {
                return ResourceManager.GetString("VV1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable_Value[1].
        /// </summary>
        internal static string VV1PEx {
            get {
                return ResourceManager.GetString("VV1PEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop_Warsoul_Item.
        /// </summary>
        internal static string Warsoul {
            get {
                return ResourceManager.GetString("Warsoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ZERO {
            get {
                return ResourceManager.GetString("ZERO", resourceCulture);
            }
        }
    }
}
